version: '3'
services:
  clubsystem:
    build: .
    volumes:
      - .venv:/src/.venv
      - .:/src
    ports:
      - 8001:8000  # ホストマシンのポート8000を、docker内のポート8000に接続する
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: tepic2022
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
      - ./configdb:/data/configdb
